//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProgramacionWeb.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pagos = new HashSet<Pago>();
        }
    
        public int ClienteId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> EdoClienteId { get; set; }
        public EstadosCliente EstadosCliente { get; set; }
        public ICollection<Pago> Pagos { get; set; }
    }
}
