//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProgramacionWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> Total { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> IVA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
